export const categories = [
  { id: '1', emoji: '🥾', title: 'Hiking' },
  { id: '3', emoji: '🎈', title: 'Ballooning' },
  { id: '2', emoji: '🛶', title: 'Kayaking' },
  { id: '4', emoji: '⛰️', title: 'Mountains' },
  { id: '15', emoji: '🧗🏼‍♂️', title: 'Rock climbing' },
  { id: '5', emoji: '🌋', title: 'Volcano' },
  { id: '6', emoji: '🏄🏻‍♂️', title: 'Surfing' },
  { id: '7', emoji: '🐦', title: 'Birding' },
  { id: '8', emoji: '🌊', title: 'Sea' },
  { id: '9', emoji: '⛷️', title: 'Skiing' },
  { id: '10', emoji: '🏌️', title: 'Golf' },
  { id: '11', emoji: '🏜️', title: 'Desert' },
  { id: '12', emoji: '⛵', title: 'Sail' },
  { id: '13', emoji: '🌳', title: 'Nature' },
  { id: '14', emoji: '🎣', title: 'Fishing' },
  { id: '16', emoji: '🔭', title: 'Star Gazing' },
];
