export * from './Search';
export * from './Login';
export * from './Card';
export * from './Home';
export * from './Profile';
export * from './Map';
export * from './Gallery';
export * from './Want';
export * from './Visited';
